### PR TITLE
Installation script.

### PR DESCRIPTION
**Pull request by DIWesser**
I've created a installation script that copies the files from the git repository into ~/.config/mpv/scripts.

The script checks for existing installations and asks for confirmation before overwriting them. It can also handle being run when the working directory is not the local git repo if someone is being silly.

### CODE REVIEW

**Comment by po5** [comment]
Thanks for the PR.
I guess the idea was to streamline the installation but it will cause extra confusion for Windows users.
The solution would be to also make a Windows script but I don't think it's worth it when the install is as simple as copying a file and a folder.
I'm also not sure I want to make assumptions about the config dir location.

**Comment by DIWesser** [comment]
My thought process was more that I'd be more likely to actually check for updates if all I have to do is run `git pull && ./install.sh`. (That, and I've been meaning to try a location aware script for a while.)

Looking at the Arch wiki, it seems safe to assume the install path. I could add a check that the path exists and prompts for a custom one thought.

All that said, fair if you don't want it. It would be confusing for some Windows users.

**Comment by po5** [comment]
Oh then look into [mpv_manager](https://github.com/po5/mpv_manager) for easy cross-platform script updating.
I want to add a nice menu to it eventually, but for now a keybind works just fine.

**Comment by DIWesser** [comment]
Nice project. Does exactly what I was looking for.

**Pull request closed without merging**
